{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xdlc-agent.serviceAccountName" . }}
  labels:
    {{- include "xdlc-agent.labels" . | nindent 4 }}
{{- end }}
