package main

import (
	"fmt"
	"strings"

	"github.com/xdlc-labs/xdlc-agent/internal/repos"
)

// branchNote is the comment written beside every scaffolded
// repos[].branch. The key is the filter incoming workflow_run
// deliveries are matched against and it is never inferred from the
// repository, so a repo whose trunk is not this branch has to say so —
// otherwise GitHub reports each delivery as accepted and the daemon
// drops it.
const branchNote = "  # branch CI runs on; must match — never guessed"

// prodBranchNote is the comment written beside every scaffolded
// repos[].prod_branch on the promote-capable profiles. The key defaults
// to "main" silently, and a repo whose production branch is anything
// else (release, production, master) would have every Promote
// fast-forward the wrong ref — so the profiles that enable Promote spell
// it out instead of leaning on the default.
const prodBranchNote = "  # promote/revert target; fast-forwarded from branch above"

// gitopsScaffoldNote is written into the promote-capable profiles
// because `xdlc init` cannot create any of it from a checkout: the
// cluster objects, and the values files a Promote carries the image tag
// between. Left unsaid, an operator who opts into gitops gets a
// daemon that fast-forwards prod and silently carries no image tag.
const gitopsScaffoldNote = `# Not scaffolded — you still have to create these by hand:
#  1. The ArgoCD Application named in argocd_app (dev namespace) and the
#     Job named in probe_job. dev-smoke gates on that Job.
#  2. The Helm values files a Promote carries the image tag between:
#       gitops/values/dev/<name>.yaml
#       gitops/values/prod/<name>.yaml
#     in each repo, each with an image.tag key. The file name must be
#     exactly repos[].name below. A service whose values file is named
#     anything else carries no tag: the daemon warns and records
#     tag_carry=no_values_file, then fast-forwards prod anyway, so prod
#     keeps its old image. Repos with no values files at all promote by
#     fast-forward only, which is a supported setup.
`

// parseInitProfile accepts ci (default), gitops, or full.
func parseInitProfile(s string) (string, error) {
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "", "ci":
		return "ci", nil
	case "gitops":
		return "gitops", nil
	case "full":
		return "full", nil
	default:
		return "", fmt.Errorf("unknown --profile %q (want ci, gitops, or full)", s)
	}
}

func starterYAML(profile string) string {
	switch profile {
	case "gitops":
		return starterConfigGitops
	case "full":
		return starterConfigFull
	default:
		return starterConfigCI
	}
}

// configFromScan renders a starter config whose repos: block is the
// scanned checkouts. Default profile is ci: gitops/full add cluster keys
// this command cannot discover from a checkout alone.
func configFromScan(found []scannedRepo, profile string) string {
	var b strings.Builder
	b.WriteString(scanHeader(profile))
	for _, r := range found {
		fmt.Fprintf(&b, "  - name: %s\n", r.Name)
		fmt.Fprintf(&b, "    github: %s\n", r.GitHub)
		fmt.Fprintf(&b, "    dir: %s\n", r.Dir)
		branch := r.Branch
		if branch == "" {
			branch = repos.DefaultBranch
		}
		fmt.Fprintf(&b, "    branch: %s%s\n", branch, branchNote)
		switch profile {
		case "gitops":
			fmt.Fprintf(&b, "    prod_branch: %s%s\n", repos.DefaultProdBranch, prodBranchNote)
			b.WriteString("    gates: [ci, dev-smoke]\n")
			fmt.Fprintf(&b, "    argocd_app: dev-%s\n", r.Name)
			b.WriteString("    probe_job: smoke-e2e\n")
		case "full":
			fmt.Fprintf(&b, "    prod_branch: %s%s\n", repos.DefaultProdBranch, prodBranchNote)
			b.WriteString("    gates: [ci, dev-smoke, prod-health]\n")
			fmt.Fprintf(&b, "    argocd_app: dev-%s\n", r.Name)
			b.WriteString("    probe_job: smoke-e2e\n")
		default:
			b.WriteString("    gates: [ci]\n")
			b.WriteString("    # argocd_app: dev-" + r.Name + "\n")
			b.WriteString("    # probe_job: smoke-e2e\n")
		}
	}
	b.WriteString(scanFooter(profile))
	return b.String()
}

func scanHeader(profile string) string {
	switch profile {
	case "gitops":
		return `# yaml-language-server: $schema=./schema/config.schema.json
# Generated by: xdlc init --scan --profile gitops
# CI Fix + DEV smoke / Promote. Fill argocd_app / probe_job if the guesses are wrong.
# API bearer: export XDLC_API_TOKEN (optional viewer: XDLC_API_VIEWER_TOKEN).
#
` + gitopsScaffoldNote + `repos:
`
	case "full":
		return `# yaml-language-server: $schema=./schema/config.schema.json
# Generated by: xdlc init --scan --profile full
# Paved road: CI + DEV smoke + prod-health. Fill cluster keys and PromQL.
# API bearer: export XDLC_API_TOKEN (optional viewer: XDLC_API_VIEWER_TOKEN).
#
` + gitopsScaffoldNote + `repos:
`
	default:
		return `# yaml-language-server: $schema=./schema/config.schema.json
# Generated by: xdlc init --scan
# CI Fix profile — add GitOps / prod with --profile gitops|full, or see https://xdlc.dev/agent/docs/gitops-argo/.
# API bearer: export XDLC_API_TOKEN (optional viewer: XDLC_API_VIEWER_TOKEN).
repos:
`
	}
}

func scanFooter(profile string) string {
	switch profile {
	case "gitops":
		return scanConfigFooterGitops
	case "full":
		return scanConfigFooterFull
	default:
		return scanConfigFooterCI
	}
}

const scanConfigFooterCI = `
server:
  addr: "127.0.0.1:8080"
  github_webhook_secret_env: GITHUB_WEBHOOK_SECRET
  require_webhook_secret: false
  # Loopback bind, so a webhook secret is not forced. To bind a
  # non-loopback address (":8080", 0.0.0.0, container, Kubernetes):
  # set require_webhook_secret: true and export GITHUB_WEBHOOK_SECRET
  # (plus ARGOCD_WEBHOOK_SECRET / ALERTMANAGER_WEBHOOK_SECRET if used).
  # The daemon refuses to start on a non-loopback addr while this is false.

gates:
  ci:
    trigger: on_push

agent:
  mode: subprocess
  provider: claude # claude | codex | cursor | gemini
  timeout: 10m
  # rules_file: ~/.xdlc/rules.md   # instructions added to every Fix prompt
  # sessions:
  #   dir: sessions               # prompt / output / diff per Fix
  #   retain: 720h
`

const scanConfigFooterGitops = `
server:
  addr: "127.0.0.1:8080"
  github_webhook_secret_env: GITHUB_WEBHOOK_SECRET
  argocd_webhook_secret_env: ARGOCD_WEBHOOK_SECRET
  require_webhook_secret: false
  # Loopback bind, so a webhook secret is not forced. To bind a
  # non-loopback address (":8080", 0.0.0.0, container, Kubernetes):
  # set require_webhook_secret: true and export GITHUB_WEBHOOK_SECRET
  # (plus ARGOCD_WEBHOOK_SECRET / ALERTMANAGER_WEBHOOK_SECRET if used).
  # The daemon refuses to start on a non-loopback addr while this is false.

gates:
  ci:
    trigger: on_push
  dev-smoke:
    trigger: on_sync
    namespace: dev
    interval: 30s

agent:
  mode: subprocess
  provider: claude # claude | codex | cursor | gemini
  timeout: 10m
`

const scanConfigFooterFull = `
server:
  addr: "127.0.0.1:8080"
  github_webhook_secret_env: GITHUB_WEBHOOK_SECRET
  argocd_webhook_secret_env: ARGOCD_WEBHOOK_SECRET
  alertmanager_webhook_secret_env: ALERTMANAGER_WEBHOOK_SECRET
  require_webhook_secret: false
  # Loopback bind, so a webhook secret is not forced. To bind a
  # non-loopback address (":8080", 0.0.0.0, container, Kubernetes):
  # set require_webhook_secret: true and export GITHUB_WEBHOOK_SECRET
  # (plus ARGOCD_WEBHOOK_SECRET / ALERTMANAGER_WEBHOOK_SECRET if used).
  # The daemon refuses to start on a non-loopback addr while this is false.

gates:
  ci:
    trigger: on_push
  dev-smoke:
    trigger: on_sync
    namespace: dev
    interval: 30s
  prod-health:
    trigger: continuous
    metrics_url: http://prometheus.your-domain.io
    thresholds:
      p95_ms: 500
      error_rate: 0.01
    interval: 30s
    p95_query: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{service="{{repo}}"}[5m])) by (le)) * 1000
    error_rate_query: sum(rate(http_requests_total{service="{{repo}}",status=~"5.."}[5m])) / sum(rate(http_requests_total{service="{{repo}}"}[5m]))

agent:
  mode: subprocess
  provider: claude # claude | codex | cursor | gemini
  timeout: 10m
`

const starterConfigCI = `# yaml-language-server: $schema=./schema/config.schema.json
# CI Fix profile (default). GitOps / prod: xdlc init --profile gitops|full
# See https://xdlc.dev/agent/docs/getting-started/. API bearer: export XDLC_API_TOKEN.
repos:
  - name: example-service
    github: xdlc-labs/example-service
    branch: ` + repos.DefaultBranch + branchNote + `
    gates: [ci]

# github:  # App preferred; GITHUB_TOKEN is PAT fallback
#   app_id: 123456
#   installation_id: 12345678
#   private_key_env: GITHUB_APP_PRIVATE_KEY

server:
  addr: "127.0.0.1:8080"
  github_webhook_secret_env: GITHUB_WEBHOOK_SECRET
  require_webhook_secret: false
  # Loopback bind, so a webhook secret is not forced. To bind a
  # non-loopback address (":8080", 0.0.0.0, container, Kubernetes):
  # set require_webhook_secret: true and export GITHUB_WEBHOOK_SECRET
  # (plus ARGOCD_WEBHOOK_SECRET / ALERTMANAGER_WEBHOOK_SECRET if used).
  # The daemon refuses to start on a non-loopback addr while this is false.

gates:
  ci:
    trigger: on_push

agent:
  mode: subprocess
  provider: claude # claude | codex | cursor | gemini
  timeout: 10m
`

const starterConfigGitops = `# yaml-language-server: $schema=./schema/config.schema.json
# GitOps profile: CI Fix + DEV smoke → Promote. See https://xdlc.dev/agent/docs/gitops-argo/.
# API bearer: export XDLC_API_TOKEN.
#
` + gitopsScaffoldNote + `repos:
  - name: example-service
    github: xdlc-labs/example-service
    branch: ` + repos.DefaultBranch + branchNote + `
    prod_branch: ` + repos.DefaultProdBranch + prodBranchNote + `
    gates: [ci, dev-smoke]
    argocd_app: dev-example-service
    probe_job: smoke-e2e

# github:  # App preferred; GITHUB_TOKEN is PAT fallback
#   app_id: 123456
#   installation_id: 12345678
#   private_key_env: GITHUB_APP_PRIVATE_KEY

server:
  addr: "127.0.0.1:8080"
  github_webhook_secret_env: GITHUB_WEBHOOK_SECRET
  argocd_webhook_secret_env: ARGOCD_WEBHOOK_SECRET
  require_webhook_secret: false
  # Loopback bind, so a webhook secret is not forced. To bind a
  # non-loopback address (":8080", 0.0.0.0, container, Kubernetes):
  # set require_webhook_secret: true and export GITHUB_WEBHOOK_SECRET
  # (plus ARGOCD_WEBHOOK_SECRET / ALERTMANAGER_WEBHOOK_SECRET if used).
  # The daemon refuses to start on a non-loopback addr while this is false.

gates:
  ci:
    trigger: on_push
  dev-smoke:
    trigger: on_sync
    namespace: dev
    interval: 30s

agent:
  mode: subprocess
  provider: claude # claude | codex | cursor | gemini
  timeout: 10m
`

const starterConfigFull = `# yaml-language-server: $schema=./schema/config.schema.json
# Full paved road. See https://xdlc.dev/agent/docs/production-loop/.
# API bearer: export XDLC_API_TOKEN.
#
` + gitopsScaffoldNote + `repos:
  - name: example-service
    github: xdlc-labs/example-service
    branch: ` + repos.DefaultBranch + branchNote + `
    prod_branch: ` + repos.DefaultProdBranch + prodBranchNote + `
    gates: [ci, dev-smoke, prod-health]
    argocd_app: dev-example-service
    probe_job: smoke-e2e

# github:  # App preferred; GITHUB_TOKEN is PAT fallback
#   app_id: 123456
#   installation_id: 12345678
#   private_key_env: GITHUB_APP_PRIVATE_KEY

server:
  addr: "127.0.0.1:8080"
  github_webhook_secret_env: GITHUB_WEBHOOK_SECRET
  argocd_webhook_secret_env: ARGOCD_WEBHOOK_SECRET
  alertmanager_webhook_secret_env: ALERTMANAGER_WEBHOOK_SECRET
  require_webhook_secret: false
  # Loopback bind, so a webhook secret is not forced. To bind a
  # non-loopback address (":8080", 0.0.0.0, container, Kubernetes):
  # set require_webhook_secret: true and export GITHUB_WEBHOOK_SECRET
  # (plus ARGOCD_WEBHOOK_SECRET / ALERTMANAGER_WEBHOOK_SECRET if used).
  # The daemon refuses to start on a non-loopback addr while this is false.

gates:
  ci:
    trigger: on_push
  dev-smoke:
    trigger: on_sync
    namespace: dev
    interval: 30s
  prod-health:
    trigger: continuous
    metrics_url: http://prometheus.your-domain.io
    thresholds:
      p95_ms: 500
      error_rate: 0.01
    interval: 30s
    p95_query: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{service="{{repo}}"}[5m])) by (le)) * 1000
    error_rate_query: sum(rate(http_requests_total{service="{{repo}}",status=~"5.."}[5m])) / sum(rate(http_requests_total{service="{{repo}}"}[5m]))

agent:
  mode: subprocess
  provider: claude # claude | codex | cursor | gemini
  timeout: 10m
`
