package main

import (
	"fmt"
	"strings"
)

// parseInitProfile accepts ci (default), gitops, or full.
func parseInitProfile(s string) (string, error) {
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "", "ci":
		return "ci", nil
	case "gitops":
		return "gitops", nil
	case "full":
		return "full", nil
	default:
		return "", fmt.Errorf("unknown --profile %q (want ci, gitops, or full)", s)
	}
}

func starterYAML(profile string) string {
	switch profile {
	case "gitops":
		return starterConfigGitops
	case "full":
		return starterConfigFull
	default:
		return starterConfigCI
	}
}

// configFromScan renders a starter config whose repos: block is the
// scanned checkouts. Default profile is ci: gitops/full add cluster keys
// this command cannot discover from a checkout alone.
func configFromScan(found []scannedRepo, profile string) string {
	var b strings.Builder
	b.WriteString(scanHeader(profile))
	for _, r := range found {
		fmt.Fprintf(&b, "  - name: %s\n", r.Name)
		fmt.Fprintf(&b, "    github: %s\n", r.GitHub)
		fmt.Fprintf(&b, "    dir: %s\n", r.Dir)
		if r.Branch != "" {
			fmt.Fprintf(&b, "    branch: %s\n", r.Branch)
		}
		switch profile {
		case "gitops":
			b.WriteString("    gates: [ci, dev-smoke]\n")
			fmt.Fprintf(&b, "    argocd_app: dev-%s\n", r.Name)
			b.WriteString("    probe_job: smoke-e2e\n")
		case "full":
			b.WriteString("    gates: [ci, dev-smoke, prod-health]\n")
			fmt.Fprintf(&b, "    argocd_app: dev-%s\n", r.Name)
			b.WriteString("    probe_job: smoke-e2e\n")
		default:
			b.WriteString("    gates: [ci]\n")
			b.WriteString("    # argocd_app: dev-" + r.Name + "\n")
			b.WriteString("    # probe_job: smoke-e2e\n")
		}
	}
	b.WriteString(scanFooter(profile))
	return b.String()
}

func scanHeader(profile string) string {
	switch profile {
	case "gitops":
		return `# yaml-language-server: $schema=./schema/config.schema.json
# Generated by: xdlc init --scan --profile gitops
# CI Fix + DEV smoke / Promote. Fill argocd_app / probe_job if the guesses are wrong.
# API bearer: export XDLC_API_TOKEN (optional viewer: XDLC_API_VIEWER_TOKEN).
repos:
`
	case "full":
		return `# yaml-language-server: $schema=./schema/config.schema.json
# Generated by: xdlc init --scan --profile full
# Paved road: CI + DEV smoke + prod-health. Fill cluster keys and PromQL.
# API bearer: export XDLC_API_TOKEN (optional viewer: XDLC_API_VIEWER_TOKEN).
repos:
`
	default:
		return `# yaml-language-server: $schema=./schema/config.schema.json
# Generated by: xdlc init --scan
# CI Fix profile — add GitOps / prod with --profile gitops|full, or see docs/gitops-argo.md.
# API bearer: export XDLC_API_TOKEN (optional viewer: XDLC_API_VIEWER_TOKEN).
repos:
`
	}
}

func scanFooter(profile string) string {
	switch profile {
	case "gitops":
		return scanConfigFooterGitops
	case "full":
		return scanConfigFooterFull
	default:
		return scanConfigFooterCI
	}
}

const scanConfigFooterCI = `
server:
  addr: ":8080"
  github_webhook_secret_env: GITHUB_WEBHOOK_SECRET
  require_webhook_secret: false # loopback only while this is false

gates:
  ci:
    trigger: on_push

agent:
  mode: subprocess
  provider: claude # claude | codex | cursor | gemini
  timeout: 10m
  # rules_file: ~/.xdlc/rules.md   # instructions added to every Fix prompt
  # sessions:
  #   dir: sessions               # prompt / output / diff per Fix
  #   retain: 720h
`

const scanConfigFooterGitops = `
server:
  addr: ":8080"
  github_webhook_secret_env: GITHUB_WEBHOOK_SECRET
  argocd_webhook_secret_env: ARGOCD_WEBHOOK_SECRET
  require_webhook_secret: false # loopback only while this is false

gates:
  ci:
    trigger: on_push
  dev-smoke:
    trigger: on_sync
    namespace: dev
    interval: 30s

agent:
  mode: subprocess
  provider: claude # claude | codex | cursor | gemini
  timeout: 10m
`

const scanConfigFooterFull = `
server:
  addr: ":8080"
  github_webhook_secret_env: GITHUB_WEBHOOK_SECRET
  argocd_webhook_secret_env: ARGOCD_WEBHOOK_SECRET
  alertmanager_webhook_secret_env: ALERTMANAGER_WEBHOOK_SECRET
  require_webhook_secret: false # loopback only while this is false

gates:
  ci:
    trigger: on_push
  dev-smoke:
    trigger: on_sync
    namespace: dev
    interval: 30s
  prod-health:
    trigger: continuous
    metrics_url: http://prometheus.your-domain.io
    thresholds:
      p95_ms: 500
      error_rate: 0.01
    interval: 30s
    p95_query: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{service="{{repo}}"}[5m])) by (le)) * 1000
    error_rate_query: sum(rate(http_requests_total{service="{{repo}}",status=~"5.."}[5m])) / sum(rate(http_requests_total{service="{{repo}}"}[5m]))

agent:
  mode: subprocess
  provider: claude # claude | codex | cursor | gemini
  timeout: 10m
`

const starterConfigCI = `# yaml-language-server: $schema=./schema/config.schema.json
# CI Fix profile (default). GitOps / prod: xdlc init --profile gitops|full
# See docs/getting-started.md. API bearer: export XDLC_API_TOKEN.
repos:
  - name: example-service
    github: your-org/example-service
    gates: [ci]

# github:  # App preferred; GITHUB_TOKEN is PAT fallback
#   app_id: 123456
#   installation_id: 12345678
#   private_key_env: GITHUB_APP_PRIVATE_KEY

server:
  addr: ":8080"
  github_webhook_secret_env: GITHUB_WEBHOOK_SECRET
  require_webhook_secret: false # loopback only while this is false

gates:
  ci:
    trigger: on_push

agent:
  mode: subprocess
  provider: claude # claude | codex | cursor | gemini
  timeout: 10m
`

const starterConfigGitops = `# yaml-language-server: $schema=./schema/config.schema.json
# GitOps profile: CI Fix + DEV smoke → Promote. See docs/gitops-argo.md.
# API bearer: export XDLC_API_TOKEN.
repos:
  - name: example-service
    github: your-org/example-service
    gates: [ci, dev-smoke]
    argocd_app: dev-example-service
    probe_job: smoke-e2e

# github:  # App preferred; GITHUB_TOKEN is PAT fallback
#   app_id: 123456
#   installation_id: 12345678
#   private_key_env: GITHUB_APP_PRIVATE_KEY

server:
  addr: ":8080"
  github_webhook_secret_env: GITHUB_WEBHOOK_SECRET
  argocd_webhook_secret_env: ARGOCD_WEBHOOK_SECRET
  require_webhook_secret: false # loopback only while this is false

gates:
  ci:
    trigger: on_push
  dev-smoke:
    trigger: on_sync
    namespace: dev
    interval: 30s

agent:
  mode: subprocess
  provider: claude # claude | codex | cursor | gemini
  timeout: 10m
`

const starterConfigFull = `# yaml-language-server: $schema=./schema/config.schema.json
# Full paved road. See docs/production-loop.md.
# API bearer: export XDLC_API_TOKEN.
repos:
  - name: example-service
    github: your-org/example-service
    gates: [ci, dev-smoke, prod-health]
    argocd_app: dev-example-service
    probe_job: smoke-e2e

# github:  # App preferred; GITHUB_TOKEN is PAT fallback
#   app_id: 123456
#   installation_id: 12345678
#   private_key_env: GITHUB_APP_PRIVATE_KEY

server:
  addr: ":8080"
  github_webhook_secret_env: GITHUB_WEBHOOK_SECRET
  argocd_webhook_secret_env: ARGOCD_WEBHOOK_SECRET
  alertmanager_webhook_secret_env: ALERTMANAGER_WEBHOOK_SECRET
  require_webhook_secret: false # loopback only while this is false

gates:
  ci:
    trigger: on_push
  dev-smoke:
    trigger: on_sync
    namespace: dev
    interval: 30s
  prod-health:
    trigger: continuous
    metrics_url: http://prometheus.your-domain.io
    thresholds:
      p95_ms: 500
      error_rate: 0.01
    interval: 30s
    p95_query: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{service="{{repo}}"}[5m])) by (le)) * 1000
    error_rate_query: sum(rate(http_requests_total{service="{{repo}}",status=~"5.."}[5m])) / sum(rate(http_requests_total{service="{{repo}}"}[5m]))

agent:
  mode: subprocess
  provider: claude # claude | codex | cursor | gemini
  timeout: 10m
`
