/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as GatesRouteImport } from './routes/gates'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as ReposIndexRouteImport } from './routes/repos.index'
import { Route as ReposIdRouteImport } from './routes/repos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesRoute = GatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const ReposIndexRoute = ReposIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReposRoute,
} as any)
const ReposIdRoute = ReposIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReposRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/activity': typeof ActivityRoute
  '/docs': typeof DocsRouteWithChildren
  '/gates': typeof GatesRoute
  '/repos': typeof ReposRouteWithChildren
  '/settings': typeof SettingsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/repos/$id': typeof ReposIdRoute
  '/docs/': typeof DocsIndexRoute
  '/repos/': typeof ReposIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/activity': typeof ActivityRoute
  '/gates': typeof GatesRoute
  '/settings': typeof SettingsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/repos/$id': typeof ReposIdRoute
  '/docs': typeof DocsIndexRoute
  '/repos': typeof ReposIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/activity': typeof ActivityRoute
  '/docs': typeof DocsRouteWithChildren
  '/gates': typeof GatesRoute
  '/repos': typeof ReposRouteWithChildren
  '/settings': typeof SettingsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/repos/$id': typeof ReposIdRoute
  '/docs/': typeof DocsIndexRoute
  '/repos/': typeof ReposIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/activity'
    | '/docs'
    | '/gates'
    | '/repos'
    | '/settings'
    | '/docs/$slug'
    | '/repos/$id'
    | '/docs/'
    | '/repos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/activity'
    | '/gates'
    | '/settings'
    | '/docs/$slug'
    | '/repos/$id'
    | '/docs'
    | '/repos'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/activity'
    | '/docs'
    | '/gates'
    | '/repos'
    | '/settings'
    | '/docs/$slug'
    | '/repos/$id'
    | '/docs/'
    | '/repos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  ActivityRoute: typeof ActivityRoute
  DocsRoute: typeof DocsRouteWithChildren
  GatesRoute: typeof GatesRoute
  ReposRoute: typeof ReposRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates': {
      id: '/gates'
      path: '/gates'
      fullPath: '/gates'
      preLoaderRoute: typeof GatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/repos/': {
      id: '/repos/'
      path: '/'
      fullPath: '/repos/'
      preLoaderRoute: typeof ReposIndexRouteImport
      parentRoute: typeof ReposRoute
    }
    '/repos/$id': {
      id: '/repos/$id'
      path: '/$id'
      fullPath: '/repos/$id'
      preLoaderRoute: typeof ReposIdRouteImport
      parentRoute: typeof ReposRoute
    }
  }
}

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface ReposRouteChildren {
  ReposIdRoute: typeof ReposIdRoute
  ReposIndexRoute: typeof ReposIndexRoute
}

const ReposRouteChildren: ReposRouteChildren = {
  ReposIdRoute: ReposIdRoute,
  ReposIndexRoute: ReposIndexRoute,
}

const ReposRouteWithChildren = ReposRoute._addFileChildren(ReposRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  ActivityRoute: ActivityRoute,
  DocsRoute: DocsRouteWithChildren,
  GatesRoute: GatesRoute,
  ReposRoute: ReposRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
